# Initial idea of repoman checks: https://github.com/mrueg/repoman-travis

# use "Trusty" as "Precise" has bash 4.2 only, which doesn't support nameref vars
sudo: required
dist: trusty
language: python
python:
    - "3.4" # repoman seems to be fastest with python-3.4
#addons:
#    apt:
#        sources:
#            - debian-sid
#        packages:
#            - shellcheck

git:
    depth: 1
branches:
    only:
        - master
        - dev
        - /^ci\//

## env config and env-based matrix
env:
    global:
        ## configurable variables
        - OVERLAY_NAME='bentoo'
    matrix:
        - PORTAGE_VER="2.3.3" REPOMAN_VER="2.3.1"
#        - SHELLCHECK=1
## final touches to the matrix
matrix:
    fast_finish: true
#    allow_failures:
#            - env: SHELLCHECK=1

cache:
    pip: true
    directories:
        - ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/
before_cache:
    - rm -v -f ${HOME}/.cache/pip/log/debug.log

# -----------------------------------------------------------------------------

before_install:
    - source .travis/setup_environment.sh

install:
    - .travis/run_install.sh

script:
    - .travis/run_tests.sh

# after_success:
#     - cd "${TRAVIS_BUILD_DIR}"
#     - .travis/setup_git.sh

# -----------------------------------------------------------------------------
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/037253afb58551e81cd0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

